# Generated by Django 2.2.3 on 2019-08-23 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20190823_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='a',
        ),
    ]
