# Generated by Django 2.2.3 on 2019-07-15 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='adres',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='settings',
            name='email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='settings',
            name='facebook',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='settings',
            name='fax',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='settings',
            name='gplus',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='settings',
            name='hakkimizdaimage',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='iletisimimage',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='instagram',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='settings',
            name='kisahakkimizda',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='kisailetisim',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='pinterest',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='settings',
            name='sehir',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='settings',
            name='smtpmail',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='settings',
            name='smtppass',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='settings',
            name='smtpport',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='settings',
            name='smtpserver',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='settings',
            name='tel',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='settings',
            name='tumblr',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='settings',
            name='twitter',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='settings',
            name='youtube',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
