# Generated by Django 2.2.3 on 2019-08-28 07:41

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_auto_20190716_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='hakkimizda',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='settings',
            name='iletisim',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
