# Generated by Django 2.2.3 on 2019-07-15 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=255)),
                ('mail', models.CharField(max_length=255)),
                ('konu', models.CharField(max_length=255)),
                ('mesaj', models.TextField(max_length=255)),
            ],
        ),
    ]
