# Generated by Django 2.2.3 on 2019-08-27 18:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='status',
            field=models.IntegerField(choices=[(1, 'New'), (2, 'Read')], default=1),
        ),
        migrations.AddField(
            model_name='contact',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
