# Generated by Django 2.2.3 on 2019-08-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_orderdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('New', 'New'), ('Canceled', 'Canceled'), ('OnShipping', 'OnShipping'), ('Completed', 'Completed'), ('Preaparing', 'Preaparing')], default='New', max_length=15),
        ),
    ]
