# Generated by Django 2.2.3 on 2019-08-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20190827_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Preaparing', 'Preaparing'), ('Accepted', 'Accepted'), ('Canceled', 'Canceled'), ('OnShipping', 'OnShipping'), ('Completed', 'Completed'), ('New', 'New')], default='New', max_length=15),
        ),
    ]
