# Generated by Django 2.2.3 on 2019-08-27 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20190827_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('OnShipping', 'OnShipping'), ('Completed', 'Completed'), ('Canceled', 'Canceled'), ('Preaparing', 'Preaparing'), ('Accepted', 'Accepted'), ('New', 'New')], default='New', max_length=15),
        ),
    ]
