# Generated by Django 2.2.3 on 2019-08-28 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20190827_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Preaparing', 'Preaparing'), ('Accepted', 'Accepted'), ('OnShipping', 'OnShipping'), ('New', 'New'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], default='New', max_length=15),
        ),
    ]
